/*************************************************************************
 * This file was generated by CRUST by an automated semantics preserving
 * translation from C/C++ to Rust
 * CRUST isn't perfect and may require manual editing
 * Check warnings and errors and refer to the official Rust Documentation
 ************************************************************************/
fn main() {
    /*Avoid using mutable variables unless it is necessary to do so
     */
    let mut a: u16 = 0;
    let mut b: u16 = 9;
    if (a == b) == true {
        //i dont care if a is equal to be :P
    }
}
