/*************************************************************************
 * This file was generated by CRUST by an automated semantics preserving
 * translation from C/C++ to Rust
 * CRUST isn't perfect and may require manual editing
 * Check warnings and errors and refer to the official Rust Documentation
 ************************************************************************/
fn main() {
    /*Avoid using mutable variables unless it is necessary to do so
     */
    let mut b: i32 = c + b + c;
    /*Avoid using mutable variables unless it is necessary to do so
     */
    let mut a: i32 = b + std::mem::size_of(i32);
}
