/*************************************************************************
 * This file was generated by CRUST by an automated semantics preserving
 * translation from C/C++ to Rust
 * CRUST isn't perfect and may require manual editing
 * Check warnings and errors and refer to the official Rust Documentation
 ************************************************************************/
struct FilePointer {
    stdin: i32,
    stdout: i32,
    stderr: i32,
    EOF: char,
}
struct A {
    a: i32,
    b: i32,
    c: i32,
    fa: f32,
}
fn main() {
    /** Declaration of a structure should be completed with initialization of it's fields
     * It should be in the following format
     * let variable:struct_name = struct_name { member1:value1, member2:value2,..}
     */
    let fp = FilePointer {
        stdin: 0i32,
        stdout: 0i32,
        stderr: 0i32,
        EOF: '_',
    };
    /** Declaration of a structure should be completed with initialization of it's fields
     * It should be in the following format
     * let variable:struct_name = struct_name { member1:value1, member2:value2,..}
     */
    let decl_a = A {
        a: 0i32,
        b: 0i32,
        c: 0i32,
        fa: 0.0f32,
    }; //do something with fp here
}
