/*************************************************************************
 * This file was generated by CRUST by an automated semantics preserving
 * translation from C/C++ to Rust
 * CRUST isn't perfect and may require manual editing
 * Check warnings and errors and refer to the official Rust Documentation
 ************************************************************************/
fn main() {
    /*Crust with Strict Mode enabled, declares all variables as immutable.
     * If you are mutating the below variable anywhere in program, please change the declaration statement as
     * let mut var_name:type=init_val;
     **/
    let i: i32 = 0;
    /*Crust with Strict Mode enabled, declares all variables as immutable.
     * If you are mutating the below variable anywhere in program, please change the declaration statement as
     * let mut var_name:type=init_val;
     **/
    let a: [i32; 4] = [1, 2, 3, 4];
    /*Crust with Strict Mode enabled, declares all variables as immutable.
     * If you are mutating the below variable anywhere in program, please change the declaration statement as
     * let mut var_name:type=init_val;
     **/
    let b: [i32; 4] = [1, 2, 3, 4];
    /*Crust with Strict Mode enabled, declares all variables as immutable.
     * If you are mutating the below variable anywhere in program, please change the declaration statement as
     * let mut var_name:type=init_val;
     **/
    let c: [i32; 4]; //matrix addition
    while i < 4 {
        c[a] = a[i] + b[i] + 100;
        i += 1;
    }
}
